package net.bingyan.campass;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CACHE.
 */
public class Cache {

    /** Not-null value. */
    private String name;
    private String json;
    private java.util.Date date;

    public Cache() {
    }

    public Cache(String name) {
        this.name = name;
    }

    public Cache(String name, String json, java.util.Date date) {
        this.name = name;
        this.json = json;
        this.date = date;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public String getJson() {
        return json;
    }

    public void setJson(String json) {
        this.json = json;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

}
