package net.bingyan.campass;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import net.bingyan.campass.Module;
import net.bingyan.campass.Cache;

import net.bingyan.campass.ModuleDao;
import net.bingyan.campass.CacheDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig moduleDaoConfig;
    private final DaoConfig cacheDaoConfig;

    private final ModuleDao moduleDao;
    private final CacheDao cacheDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        moduleDaoConfig = daoConfigMap.get(ModuleDao.class).clone();
        moduleDaoConfig.initIdentityScope(type);

        cacheDaoConfig = daoConfigMap.get(CacheDao.class).clone();
        cacheDaoConfig.initIdentityScope(type);

        moduleDao = new ModuleDao(moduleDaoConfig, this);
        cacheDao = new CacheDao(cacheDaoConfig, this);

        registerDao(Module.class, moduleDao);
        registerDao(Cache.class, cacheDao);
    }
    
    public void clear() {
        moduleDaoConfig.getIdentityScope().clear();
        cacheDaoConfig.getIdentityScope().clear();
    }

    public ModuleDao getModuleDao() {
        return moduleDao;
    }

    public CacheDao getCacheDao() {
        return cacheDao;
    }

}
