package net.bingyan.campass;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MODULE.
 */
public class Module {

    private Long id;
    /** Not-null value. */
    private String name;
    private Integer frequency;
    private Integer iconid;
    private String classname;

    public Module() {
    }

    public Module(Long id) {
        this.id = id;
    }

    public Module(Long id, String name, Integer frequency, Integer iconid, String classname) {
        this.id = id;
        this.name = name;
        this.frequency = frequency;
        this.iconid = iconid;
        this.classname = classname;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public Integer getFrequency() {
        return frequency;
    }

    public void setFrequency(Integer frequency) {
        this.frequency = frequency;
    }

    public Integer getIconid() {
        return iconid;
    }

    public void setIconid(Integer iconid) {
        this.iconid = iconid;
    }

    public String getClassname() {
        return classname;
    }

    public void setClassname(String classname) {
        this.classname = classname;
    }

}
